#!/usr/bin/env python3

'''
Clone repositories and reset to given commit
Copyright 2016, Holger Dell
Licensed under GPLv3.
'''

import os
import yaml
import argparse
import subprocess

def main():
    path=os.path.dirname(os.path.realpath(__file__))

    parser = argparse.ArgumentParser()
    parser.add_argument("path", help=".yaml file containing submission data")
    parser.add_argument("submission", help="submission number", nargs='?')
    parser.add_argument("field", help="field", default="s", nargs='?')
    args = parser.parse_args()

    with open(args.path,'r') as f:
        submissions=yaml.load(f)
        if args.submission == None:
            for s in submissions:
                    print(str(s))
        else:
            assert(args.field != None)
            if args.field != 'configurations':
                print(str(submissions[int(args.submission)][args.field]))
            else:
                for c in submissions[int(args.submission)][args.field]:
                    print('{:s} {:s} {:s}'.format(c['mode'],c['se_or_pa'],c['executable']))

if __name__ == '__main__':
    main()
